name: CI Laravel
on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
      - name: Audit des dépendances
        run: composer audit
